name: monitor-prod
on:
  schedule:
    - cron: '12 */6 * * *' # At minute 12 past every 6th hour.
  workflow_dispatch:
jobs:
  prod-monitoring:
    runs-on: ubuntu-latest
    env:
      NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ci-cd/requirements.txt
      - name: Get monitoring metadata
        run: python ci-cd/monitoring.py
      - name: Get monitoring metadata for another model
        run: python ci-cd/monitoring_2.py