name: retrain-model
on:
  schedule:
    - cron: '12 */9 * * *' # At minute 12 past every 9th hour.
  workflow_dispatch:
jobs:
  prod-monitoring:
    runs-on: ubuntu-latest
    env:
      NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ci-cd/retrain-requirements.txt
      - name: Check and retrain model
        run: python ci-cd/re-training.py